name: Multi-Job Workflow

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod  # 👈 references the GitHub environment
    steps:
      - name: Deploy App
        run: echo "Deploying to PROD"
